### ISSUE TITLE
wow!

### ISSUE THREAD

**Issue by fdncred** [ehdevries/panache-git#5]
I just wanted to say that I love it and great job! It's no small task to create a custom prompt script in nushell, especially with git status. I created oh-my.nu and I'm working on version 2 now so I know how difficult it is. Anyway, I just wanted to drop by and say, congrats! and good job!

**Comment by ehdevries** [comment]
Thanks so much! This really means a lot. 😊 It's certainly been a good amount of work, but also loads of fun. Using Nushell is such a delightful experience, and it keeps getting better. I'll have to give oh-my.nu a try!
